# Generated by Django 5.1.6 on 2025-03-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('MNC', 'MNC'), ('Startup', 'Startup'), ('Service', 'Service'), ('Product', 'Product')], max_length=100)),
                ('founded', models.DateField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
